apiVersion: v1
kind: Pod
metadata: 
   name: jiraserver
spec:
   containers:
     - name: jiraserver
       image: nginx
       ports:
         - containerPort: 80
       env:
        - name: project
          valueFrom:
             configMapKeyRef:
                name: ssm-configmap
                key: project
        - name: team
          valueFrom:
             configMapKeyRef:
                name: ssm-configmap
                key: team

