apiVersion: v1
kind: Pod
metadata: 
   name: confluence
spec:
   containers:
     - name: confluence
       image: nginx
       ports:
         - containerPort: 80
       envFrom:
         - configMapRef:
                name: ssm-configmap
              

