apiVersion: v1
kind: Pod
metadata: 
  name: resources
  labels:
     env: prod
     owner: dinesh
spec: 
   containers:
     - name: resources
       image: alpine
       ports:
         - containerPort: 80
       resources:
            requests: 
               cpu: "250m"
               memory: "64Mi"
            limits:
                cpu: "500m"
                memory: "100Mi"
