apiVersion: v1
kind: Pod
metadata: 
   name: hgx-vcenter
spec:
   containers:
     - name: hgx-vcenter
       image: nginx
       ports:
         - containerPort: 80
       envFrom:
         - secretRef:
                name: secret-store
              

