apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer
  labels:
    name: loadbalancer
    project: signature
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
   name: loadbalancer
   project: signature
  ports:
    - protocol: TCP
      port: 80

