apiVersion: v1
kind: Pod
metadata:
  name: nodeport
  labels:
    name: nodeport
    project: signature
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
   name: nodeport
   project: signature
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30201
