apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: roboshop
  template:
    metadata:
      labels:
        tier: frontend
        app: roboshop
    spec:
      containers:
      - name: replicaset
        image: nginx
